# Generated by Django 6.0.7 on 2026-08-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report_attachment_report_comment_report_report_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='video',
        ),
    ]
